version: '3.1'

services:

  db:
    image: postgres:13.7
    container_name: analytics-postgres
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'test_db'
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    container_name: analytics-adminer
    restart: always
    ports:
      - 8080:8080
