// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/task-msg-v1.proto

package analytics

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnalyticAPIClient is the client API for AnalyticAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticAPIClient interface {
	WriteMessage(ctx context.Context, in *WriteMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type analyticAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticAPIClient(cc grpc.ClientConnInterface) AnalyticAPIClient {
	return &analyticAPIClient{cc}
}

func (c *analyticAPIClient) WriteMessage(ctx context.Context, in *WriteMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/analytics.v1.AnalyticAPI/WriteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticAPIServer is the server API for AnalyticAPI service.
// All implementations must embed UnimplementedAnalyticAPIServer
// for forward compatibility
type AnalyticAPIServer interface {
	WriteMessage(context.Context, *WriteMessageRequest) (*empty.Empty, error)
	mustEmbedUnimplementedAnalyticAPIServer()
}

// UnimplementedAnalyticAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticAPIServer struct {
}

func (UnimplementedAnalyticAPIServer) WriteMessage(context.Context, *WriteMessageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteMessage not implemented")
}
func (UnimplementedAnalyticAPIServer) mustEmbedUnimplementedAnalyticAPIServer() {}

// UnsafeAnalyticAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticAPIServer will
// result in compilation errors.
type UnsafeAnalyticAPIServer interface {
	mustEmbedUnimplementedAnalyticAPIServer()
}

func RegisterAnalyticAPIServer(s grpc.ServiceRegistrar, srv AnalyticAPIServer) {
	s.RegisterService(&AnalyticAPI_ServiceDesc, srv)
}

func _AnalyticAPI_WriteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticAPIServer).WriteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/analytics.v1.AnalyticAPI/WriteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticAPIServer).WriteMessage(ctx, req.(*WriteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticAPI_ServiceDesc is the grpc.ServiceDesc for AnalyticAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticAPI",
	HandlerType: (*AnalyticAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteMessage",
			Handler:    _AnalyticAPI_WriteMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task-msg-v1.proto",
}
